# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Luke Peter
tagline:          'Young Blood Old Truth'
description:      'A blog devoted to living out real theology as a young adult'
url:              http://lukepeter.com
baseurl:          /

author:
  name:           'Luke Peter'
  url:            https://lukepeter.com

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
