# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luke Peter
tagline:          'Young Blood Old Truth'
description:      'A blog devoted to living out real theology as a young adult'
url:              http://lpg0.github.io
baseurl:          http://lukepeter.com

# Sitemaps
plugins:
  - jekyll-sitemap

author:
  name:           'Luke Peter'
  url:            https://lukepeter.com

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/lpg0/lukepeter
