# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Luke Peter
tagline:          'Young Blood Old Truth'
description:      'A blog devoted to living out real theology as a young adult'
baseurl: ""
url: "https://lpg0.github.io"

author:
  name:           'Luke Peter'
  url:            https://lukepeter.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/lpg0/lukepeter
